### ISSUE TITLE
[BUG]: JsonPatch replace operations with properties having null values throws exception

### ISSUE THREAD

**Issue by reecebradley** [Stillpoint-Software/hyperbee.json#88]
### Current Behavior

# Overview
The value `null` is a valid value for a json property when performing `jsonPatch.Apply`. Instead I receive:

```text
Hyperbee.Json.Patch.JsonPatchException: The 'value' property was missing.
```

### Expected Behavior

Null should be treated like any other value and thus should not throw `Hyperbee.Json.Patch.JsonPatchException`.

### Steps To Reproduce

Sample:

```json
[
  {
    "op": "replace",
    "path": "/firstName",
    "value": null
  }
]
```

I borrowed a test from the solution in the repo:

```csharp
    [TestMethod]
    public void Replace_WhenValueProperty_WithNull()
    {
        var source = JsonNode.Parse(
            """
            {
                "first": "John"
            }
            """ );

        var patch = new JsonPatch(
            new PatchOperation( PatchOperationType.Replace, "/first", null, null ) // null is the value, throws error
        );

        patch.Apply( source );

         Assert.AreEqual( null, source!["first"] );
    }
```

```text
Test method Hyperbee.Json.Tests.Patch.JsonPatchTests.Replace_WhenValueProperty_WithNull threw exception: 
Hyperbee.Json.Patch.JsonPatchException: The 'value' property was missing.
    at Hyperbee.Json.Patch.JsonPatch.PatchValue(PatchOperation patch) in /repos/src/Hyperbee.Json/Patch/JsonPatch.cs:line 420
   at Hyperbee.Json.Patch.JsonPatch.ReplaceOperation(JsonNode node, PatchOperation patch, Action`1 undo) in /repos/src/Hyperbee.Json/Patch/JsonPatch.cs:line 365
   at Hyperbee.Json.Patch.JsonPatch.ApplyInternal(JsonNode node, IEnumerable`1 patches, Action`1 undo) in /repos/src/Hyperbee.Json/Patch/JsonPatch.cs:line 79
   at Hyperbee.Json.Patch.JsonPatch.Apply(JsonNode node, List`1 patches) in /repos/src/Hyperbee.Json/Patch/JsonPatch.cs:line 39
   at Hyperbee.Json.Patch.JsonPatch.Apply(JsonNode node) in /repos/src/Hyperbee.Json/Patch/JsonPatch.cs:line 23
   at Hyperbee.Json.Tests.Patch.JsonPatchTests.Replace_WhenValueProperty_WithNull() in /repos/test/Hyperbee.Json.Tests/Patch/JsonPatchTests.cs:line 902
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

### Anything else?

When simply doing

`var patchOperations = JsonDiff<JsonNode>.Diff( source, target );`

where target has null for a property, the generated JsonPatch operations are correct. See below

```csharp
    public TestContext TestContext { get; set; }
    [TestMethod]
    public void Replact_Compare_SourceToTarget()
    {
        var source = JsonNode.Parse(
            """
            {
                "first": "John"
            }
            """ );

        var target = JsonNode.Parse(
            """
            {
                "first": null
            }
            """ );


        var patchOperations = JsonDiff<JsonNode>.Diff( source, target );
        var patchJson = JsonSerializer.Serialize( patchOperations );

        TestContext.WriteLine( patchJson );
        // outputs [{"op":"replace","path":"/first","value":null}]

        Assert.Fail(); // to see output in vscode

    }
```

**Comment by MattEdwardsWaggleBee** [comment]
Should be part of v3.0.1, thanks fo you help.
